/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testjogl;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class NotValidDialog extends javax.swing.JDialog {

    /**
     * Creates new form NotValidDialog
     */
    public NotValidDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension d = toolkit.getScreenSize();
        int x = (d.width - this.getWidth()) / 2;
        int y = (d.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitScrumbleBtn = new javax.swing.JButton();
        scrumbleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        exitScrumbleBtn.setBorderPainted(false);
        exitScrumbleBtn.setContentAreaFilled(false);
        exitScrumbleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitScrumbleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitScrumbleBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitScrumbleBtn);
        exitScrumbleBtn.setBounds(353, 30, 70, 70);

        scrumbleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/Scrumble.png"))); // NOI18N
        scrumbleLabel.setMinimumSize(new java.awt.Dimension(440, 230));
        scrumbleLabel.setPreferredSize(new java.awt.Dimension(440, 230));
        getContentPane().add(scrumbleLabel);
        scrumbleLabel.setBounds(10, 11, 440, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitScrumbleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitScrumbleBtnActionPerformed
dispose();    }//GEN-LAST:event_exitScrumbleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotValidDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotValidDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotValidDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotValidDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NotValidDialog dialog = new NotValidDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitScrumbleBtn;
    private javax.swing.JLabel scrumbleLabel;
    // End of variables declaration//GEN-END:variables
}
