/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testjogl;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class PracticeFinishDialog extends javax.swing.JDialog {

    /**
     * Creates new form PracticeFinishDialog
     */
    public PracticeFinishDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension d = toolkit.getScreenSize();
        int x = (d.width - this.getWidth()) / 2;
        int y = (d.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        practiceOkbtn = new javax.swing.JButton();
        practiceOverLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 185));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(410, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        practiceOkbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/okYouWon.png"))); // NOI18N
        practiceOkbtn.setBorder(null);
        practiceOkbtn.setBorderPainted(false);
        practiceOkbtn.setContentAreaFilled(false);
        practiceOkbtn.setOpaque(true);
        practiceOkbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/okYouWonP.png"))); // NOI18N
        practiceOkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practiceOkbtnActionPerformed(evt);
            }
        });
        getContentPane().add(practiceOkbtn);
        practiceOkbtn.setBounds(150, 120, 110, 40);

        practiceOverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/Practice.png"))); // NOI18N
        practiceOverLabel.setMinimumSize(new java.awt.Dimension(410, 185));
        practiceOverLabel.setPreferredSize(new java.awt.Dimension(410, 185));
        getContentPane().add(practiceOverLabel);
        practiceOverLabel.setBounds(0, -60, 490, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void practiceOkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practiceOkbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        ((CubeFrame) getParent()).dispose();
        new MainScreen().setVisible(true);

    }//GEN-LAST:event_practiceOkbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticeFinishDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticeFinishDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticeFinishDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticeFinishDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PracticeFinishDialog dialog = new PracticeFinishDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton practiceOkbtn;
    private javax.swing.JLabel practiceOverLabel;
    // End of variables declaration//GEN-END:variables
}
