/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testjogl;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Idansa
 */
public class QuitDialog extends javax.swing.JDialog {

    /**
     * Creates new form quitDialog
     */
    public QuitDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension d = toolkit.getScreenSize();
        int x = (d.width - this.getWidth()) / 2;
        int y = (d.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quitNoBtn = new javax.swing.JButton();
        quitYesBtn = new javax.swing.JButton();
        quitLable = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(450, 250));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 250));
        getContentPane().setLayout(null);

        quitNoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGameNOn1.png"))); // NOI18N
        quitNoBtn.setBorderPainted(false);
        quitNoBtn.setContentAreaFilled(false);
        quitNoBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGameNOp.png"))); // NOI18N
        quitNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitNoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(quitNoBtn);
        quitNoBtn.setBounds(200, 120, 70, 60);

        quitYesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGameYESn.png"))); // NOI18N
        quitYesBtn.setBorderPainted(false);
        quitYesBtn.setContentAreaFilled(false);
        quitYesBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGameYESp.png"))); // NOI18N
        quitYesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitYesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(quitYesBtn);
        quitYesBtn.setBounds(120, 110, 70, 80);

        quitLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGame.png"))); // NOI18N
        getContentPane().add(quitLable);
        quitLable.setBounds(0, 0, 400, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitNoBtnActionPerformed
        dispose();

    }//GEN-LAST:event_quitNoBtnActionPerformed

    private void quitYesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitYesBtnActionPerformed
        new MainScreen().setVisible(true);
        if (getParent() instanceof FaceColorsSelectScreen) {
            ((FaceColorsSelectScreen) getParent()).dispose();

        }
        if (getParent() instanceof CubeFrame) {
            ((CubeFrame) getParent()).dispose();

        }

        this.dispose();
    }//GEN-LAST:event_quitYesBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel quitLable;
    private javax.swing.JButton quitNoBtn;
    private javax.swing.JButton quitYesBtn;
    // End of variables declaration//GEN-END:variables
}
