/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testjogl;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class RestartDialog extends javax.swing.JDialog {

    private Renderer renderer;

    public RestartDialog(java.awt.Frame parent, boolean modal, Renderer renderer) {
        super(parent, modal);

        initComponents();
        this.renderer = renderer;
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension d = toolkit.getScreenSize();
        int x = (d.width - this.getWidth()) / 2;
        int y = (d.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesRestartBtn = new javax.swing.JButton();
        noRestartBtn = new javax.swing.JButton();
        restartLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(430, 240));
        setResizable(false);
        getContentPane().setLayout(null);

        yesRestartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGameYESn.png"))); // NOI18N
        yesRestartBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        yesRestartBtn.setBorderPainted(false);
        yesRestartBtn.setContentAreaFilled(false);
        yesRestartBtn.setMinimumSize(new java.awt.Dimension(60, 60));
        yesRestartBtn.setPreferredSize(new java.awt.Dimension(60, 60));
        yesRestartBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGameYESp.png"))); // NOI18N
        yesRestartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRestartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(yesRestartBtn);
        yesRestartBtn.setBounds(120, 123, 60, 60);

        noRestartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGameNOn.png"))); // NOI18N
        noRestartBtn.setToolTipText("");
        noRestartBtn.setBorderPainted(false);
        noRestartBtn.setContentAreaFilled(false);
        noRestartBtn.setMaximumSize(new java.awt.Dimension(60, 60));
        noRestartBtn.setMinimumSize(new java.awt.Dimension(60, 60));
        noRestartBtn.setPreferredSize(new java.awt.Dimension(60, 60));
        noRestartBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/QuitGameNOp.png"))); // NOI18N
        noRestartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRestartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(noRestartBtn);
        noRestartBtn.setBounds(200, 123, 60, 60);

        restartLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/Restart.png"))); // NOI18N
        restartLable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(restartLable);
        restartLable.setBounds(0, 0, 400, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesRestartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRestartBtnActionPerformed
         renderer.refresh();
        dispose();

    }//GEN-LAST:event_yesRestartBtnActionPerformed

    private void noRestartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRestartBtnActionPerformed
        dispose();
    }//GEN-LAST:event_noRestartBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton noRestartBtn;
    private javax.swing.JLabel restartLable;
    private javax.swing.JButton yesRestartBtn;
    // End of variables declaration//GEN-END:variables
}
