/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testjogl;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class YouLoseDialog extends javax.swing.JDialog {

    /**
     * Creates new form youLoseDialog
     */
    public YouLoseDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension d = toolkit.getScreenSize();
        int x = (d.width - this.getWidth()) / 2;
        int y = (d.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lostBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 240));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(420, 220));
        setResizable(false);
        getContentPane().setLayout(null);

        lostBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/okYouWon.png"))); // NOI18N
        lostBtn.setBorder(null);
        lostBtn.setBorderPainted(false);
        lostBtn.setContentAreaFilled(false);
        lostBtn.setPreferredSize(new java.awt.Dimension(110, 59));
        lostBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/okYouWonP.png"))); // NOI18N
        lostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lostBtn);
        lostBtn.setBounds(140, 140, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GamePics/youLostResized.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okYouLostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okYouLostBtnActionPerformed
//              new MainScreen().setVisible(true);
                ((MultiPlayerFrame) getParent()).dispose();    }//GEN-LAST:event_okYouLostBtnActionPerformed

    private void lostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostBtnActionPerformed
        // TODO add your handling code here:
        new MainScreen().setVisible(true);
                ((CubeFrame) getParent()).dispose(); 
    }//GEN-LAST:event_lostBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouLoseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouLoseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouLoseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouLoseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                YouLoseDialog dialog = new YouLoseDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lostBtn;
    // End of variables declaration//GEN-END:variables
}
